
ENDTITLE
						LEAX	ENDTITLE_MESSAGE_1,PCR
						LBSR	SHOWCASE_MESSAGE
						LEAX	ENDTITLE_MESSAGE_2,PCR
						LBSR	SHOWCASE_MESSAGE
						LEAX	ENDTITLE_MESSAGE_3,PCR
						LBSR	SHOWCASE_MESSAGE
						LEAX	ENDTITLE_MESSAGE_4,PCR
						LBSR	SHOWCASE_MESSAGE
						RTS



; y=16,x=64  32,94  40,118  54,128


ENDTITLE_MESSAGE_1
						FCB		63
						FDB		48/8+16*40
						FCB		"'DUCKY IS BACK' END"
						FCB		0

ENDTITLE_MESSAGE_2
						FCB		63
						FDB		96/8+32*40
						FCB		"by CaptainYS"
						FCB		0

ENDTITLE_MESSAGE_3
						FCB		63
						FDB		96/8+40*40
						FCB		"HTTP://WWW.YSFLIGHT.COM"
						FCB		0

ENDTITLE_MESSAGE_4
						FCB		63
						FDB		112/8+54*40
						FCB		"THANK YOU FOR WATCHING!"
						FCB		0
