						ORG		$100

BIOSCALL_RESTORE		EQU		$FE02
BIOSCALL_WRITESECTOR	EQU		$FE05
BIOSCALL_READSECTOR		EQU		$FE08

BIOSCMD_READSECTOR		EQU		10
BIOSCMD_WRITESECTOR		EQU		9
BIOSCMD_RESTORE			EQU		8

LOADER_TOP				EQU		$1000

						ORCC	#$50
						LDS		#$100

						LDA		#$FD
						TFR		A,DP

						LDX		#LOADER_TOP
						STX		BIOS_ADDR,PCR
READ_LOOP				LEAX	BIOS_TABLE,PCR
						JSR		BIOSCALL_READSECTOR
						INC		BIOS_ADDR,PCR
						INC		BIOS_SECTOR,PCR
						LDA		BIOS_SECTOR,PCR
						CMPA	#17
						BNE		READ_LOOP

						JMP		LOADER_TOP

BIOS_TABLE				FCB		BIOSCMD_READSECTOR
						FCB		0					; Error Return
BIOS_ADDR				FDB		$1000				; Data Pointer
						FCB		0					; Track
BIOS_SECTOR				FCB		9					; Sector
						FCB		0					; Side
						FCB		0					; Drive


