IO_IRQ_MASK				EQU		$FD02
IO_IRQ_SOURCE			EQU		$FD03
IO_BEEP					EQU		$FD03

IO_URARAM				EQU		$FD0F

IO_SCREEN_MODE			EQU		$FD12
IO_SUBSYS_MONITOR_TYPE	EQU		$FD13

IO_ANALOG_PALETTE_CODE	EQU		$FD30
IO_ANALOG_PALETTE_BLUE	EQU		$FD32
IO_ANALOG_PALETTE_RED	EQU		$FD33
IO_ANALOG_PALETTE_GREEN	EQU		$FD34

IO_MMR_CONTROL			EQU		$FD93
IO_MMR_SEGMENT			EQU		$FD90
IO_MMR_TOP				EQU		$FD80
