
;						Input		Y: Command location to add
PRINTTEST_ADD_COMMAND
						LEAX	PRINTTEST_DATA,PCR
						LDB		#PRINTTEST_DATA_END-PRINTTEST_DATA
PRINTTEST_ADD_COMMAND_LOOP
						LDA		,X+
						STA		,Y+
						DECB
						BNE		PRINTTEST_ADD_COMMAND_LOOP
						RTS


PRINTTEST_DATA
						FCB		LINE_CMD_SELECT_BANK1
						FCB		LINE_CMD_PRINT
						FCB		63											; Color
						FCB		PRINTTEST_STRING_END-PRINTTEST_STRING_BEGIN ; #Chrs
						FDB		$0											; VRAM ADDR
PRINTTEST_STRING_BEGIN
						FCB		"PRINT TEST"
PRINTTEST_STRING_END
						FCB		LINE_CMD_SELECT_BANK0
						FCB		LINE_CMD_2D_END_OF_CMDSET
PRINTTEST_DATA_END

