IO_SUB_READY_BUSY		EQU		$D40A

IO_SUB_HWDRW_COMMAND	EQU		$D410
IO_SUB_HWDRW_COLOR		EQU		$D411
IO_SUB_HWDRW_MASK		EQU		$D412
IO_SUB_HWDRW_COLORMASK0	EQU		$D413
IO_SUB_HWDRW_COLORMASK1	EQU		$D414
IO_SUB_HWDRW_COLORMASK2	EQU		$D415
IO_SUB_HWDRW_COLORMASK3	EQU		$D416
IO_SUB_HWDRW_COLORMASK4	EQU		$D417
IO_SUB_HWDRW_COLORMASK5	EQU		$D418
IO_SUB_HWDRW_COLORMASK6	EQU		$D419
IO_SUB_HWDRW_COLORMASK7	EQU		$D41A
IO_SUB_HWDRW_BANKMASK	EQU		$D41B
IO_SUB_HWDRW_TILEPTN0	EQU		$D41C
IO_SUB_HWDRW_TILEPTN1	EQU		$D41D
IO_SUB_HWDRW_TILEPTN2	EQU		$D41E
IO_SUB_HWDRW_OFFSET		EQU		$D420

IO_SUB_HWDRW_LINESTYLE	EQU		$D422
IO_SUB_HWDRW_LINEX0		EQU		$D424
IO_SUB_HWDRW_LINEY0		EQU		$D426
IO_SUB_HWDRW_LINEX1		EQU		$D428
IO_SUB_HWDRW_LINEY1		EQU		$D42A

IO_SUB_HWDRW_LINESTATE	EQU		$D430		; Read

IO_SUB_VRAM_BANKSELECT	EQU		$D430		; Write
